android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4
android.native.buildOutput=verbose

KEYSTORE_FILE=auraflow-key.jks
KEYSTORE_PASSWORD=auraflowsukisu
KEY_ALIAS=auraflow-key
KEY_PASSWORD=auraflowsukisu
